### ISSUE TITLE
Unable to set MySql database name

### ISSUE THREAD

**Issue by EdOverride** [brianmario/mysql2#1116]
### Steps to reproduce
1. Run command
```
rails _6.0.2.2_ new test_abc
```

2. Add to `Gemfile`: `gem 'mysql2', '0.5.3'`

3. Run `bundle install && yarn install`

4. Edit `config/database.yml` to:
```yaml
development:
  adapter: mysql2
  encoding: utf8
  sql_mode: TRADITIONAL
  variables:
    sql_mode: TRADITIONAL
  host: localhost
  port: 3306
  username: root
  password: develop
  database: rails_test-name_development
```

5) Run `rails db:create`

Result:
```
Created database 'localhost'
```

### System configuration
**Rails version**: Tested and issue persists on rails versions `6.0.2.2` and `5.2.4.1`

**Ruby version**:ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

**mysql2 gem version**: this issue happens on gem's version `0.4.4`, `0.4.10` and `0.5.3`.
