### ISSUE TITLE
mysql80: Mysql2::Client session_track fails on mysql >= 8.0.20 or 8.0.21?

### ISSUE THREAD

**Issue by junaruga** [brianmario/mysql2#1165]
I like to open the ticket of this test failure on mysql80 case, coming from https://github.com/brianmario/mysql2/pull/1154#issuecomment-759568657 . Actually I see this issue happens on the current Travis too.

```
Failures:
  1) Mysql2::Client session_track returns multiple session track type values when available
     Failure/Error: expect(res).to eq(["________"])

       expected: ["________"]
            got: nil
     
       (compared using ==)
     # ./spec/mysql2/client_spec.rb:1053:in `block (3 levels) in <top (required)>'
```

Seeing [the history of builds](https://travis-ci.org/github/brianmario/mysql2/builds).

* With mysql-server 8.0.19: ok : [Travis log](https://travis-ci.org/github/brianmario/mysql2/jobs/671107235#L764).
* With mysql-server 8.0.21: failure : [Travis log](https://travis-ci.org/github/brianmario/mysql2/jobs/725350411#L686).
* With mysql-server 8.0.23: failure : [Travis log](https://travis-ci.org/github/brianmario/mysql2/jobs/758232282#L980).
