### ISSUE TITLE
Occasional 'Mysql2::Error: Malformed packet' errors on simple selects

### ISSUE THREAD

**Issue by cdekker** [brianmario/mysql2#715]
Since upgrading to 0.3.20 about a month ago on my production environment I started getting these errors randomly.

```
An ActiveRecord::StatementInvalid occurred in templates#test_invoice:

  Mysql2::Error: Malformed packet: SELECT `permissions`.`pkey` FROM `permissions`  WHERE `permissions`.`user_id` = 121 AND `permissions`.`client_id` = 37
  activerecord (3.2.22) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
```

Sometimes I get these errors on similar queries:
      Mysql2::Error: Lost connection to MySQL server during query:

They happen infrequent enough to be unable to reproduce them. At first I thought this was related to server RAM running out, but this doesn't seem to be the case after increasing the RAM and the errors still occuring.

Similarly, sometimes around those errors, also Rails errors start to creep up in core parts that normally work fine.
```
A NoMethodError occurred in invoice_batches#show:

  undefined method `fields' for nil:NilClass
  activerecord (3.2.22) lib/active_record/connection_adapters/mysql2_adapter.rb:218:in `exec_query'
```

This is my database.yml:
```
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: (...)
  pool: 5
  username: (...)
  password: (...)
  host: localhost
  flags: <%= 65536 | 131072 %>
```
