### ISSUE TITLE
Incorrect database name set/read on production 

### ISSUE THREAD

**Issue by nextpulse** [brianmario/mysql2#999]
The following in database.yml (actual value edited)

```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reconnect: true

production:
  <<: *default
  database: mydb
  username: user
  password: password
  host: somerds.amazonaws.com
```

I ran `rake db:migrate RAILS_ENV=production --trace` and kept getting client denied. (The db info are valid as I can connect when using mysql command line).

Did a quick debug and added the following to client.rb (line 90):

```
warn opts.inspect
 connect user, pass, host, port, database, socket, flags, conn_attrs
```

The output had the database name same as the hostname.

`{:adapter=>"mysql2", :encoding=>"utf8", :pool=>5, :reconnect=>true, :database=>"somerds.amazonaws.com", :username=>"user", :password=>password, :host=>"somerds.amazonaws.com", :flags=>2, :connect_timeout=>120}`

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.14.1
  - RUBY VERSION: 2.4.4 (2018-03-28 patchlevel 296) [x86_64-linux-gnu]
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux

Rails 5.1.4

Any ideas before I dive deeper to debug?
